### ISSUE TITLE
Error Rendering in React Tests: pragma and pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by Mercury2699** [jossmac/react-toast-notifications#171]
The test looks like this:
```
import { render } from "@testing-library/react";
import { ToastProvider } from "react-toast-notifications";
import App from "./App";

test("renders", () => {
  render(
  <ToastProvider
    placement={"bottom-center"}
  >
    <App />
  </ToastProvider>
  );
});
```
I receive error:
```
SyntaxError: ./node_modules/react-toast-notifications/dist/ToastContainer.js: pragma and pragmaFrag cannot be set when runtime is automatic.
    > 1 | 'use strict';
        | ^
      2 |
      3 | Object.defineProperty(exports, "__esModule", {
      4 |   value: true

      at File.buildCodeFrameError (node_modules/@babel/core/lib/transformation/file/file.js:250:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/lib/path/index.js:138:21)
      at PluginPass.enter (node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:163:28)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:175:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:92:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:116:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:85:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:144:19)
```

Similar Question on Stackoverflow: https://stackoverflow.com/questions/67308174/react-tests-not-running-pragma-and-pragmafrag-cannot-be-set-when-runtime-is-au

**Comment by arleyGuoLei** [comment]
me too
